import { NextResponse } from 'next/server'

const marketplaceTemplates = [
  {
    id: 'digital-agency-v2',
    name: 'Digital Agency Pro',
    description: 'Modern digital agency template with hero, services, portfolio, testimonials, and contact sections. Perfect for creative agencies and freelancers.',
    previewImage: '/templates/previews/digital-agency-pro.jpg',
    version: '2.1.0',
    category: 'agency',
    tags: ['modern', 'creative', 'portfolio', 'services'],
    downloadUrl: 'local://digital-agency',
    author: 'Perissos Team',
    authorUrl: 'https://perissos.dev',
    rating: 4.9,
    downloads: 2847,
    lastUpdated: '2026-01-15',
    local: true,
  },
  {
    id: 'food-express-v1',
    name: 'Food Express',
    description: 'Restaurant template with menu highlights, reservations, gallery, testimonials, and location sections. Warm design with elegant typography.',
    previewImage: '/templates/previews/food-express.jpg',
    version: '1.0.0',
    category: 'business',
    tags: ['restaurant', 'menu', 'reservations', 'food'],
    downloadUrl: 'local://food-express',
    author: 'Perissos Team',
    authorUrl: 'https://perissos.dev',
    rating: 4.5,
    downloads: 650,
    lastUpdated: '2026-02-10',
    local: true,
  },
  {
    id: 'optica-plus-v1',
    name: 'Optica+',
    description: 'Professional optician and eye care clinic template with services, doctor profiles, appointment booking, FAQ, and pricing sections.',
    previewImage: '/templates/previews/optica-plus.jpg',
    version: '1.0.0',
    category: 'business',
    tags: ['medical', 'healthcare', 'optician', 'clinic'],
    downloadUrl: 'local://optica-plus',
    author: 'Perissos Team',
    authorUrl: 'https://perissos.dev',
    rating: 4.6,
    downloads: 320,
    lastUpdated: '2026-03-05',
    local: true,
  },
  {
    id: 'saas-landing-v1',
    name: 'SaaS Landing Page',
    description: 'High-converting SaaS landing page with feature highlights, pricing tables, testimonials, and CTA sections. Built for software companies.',
    previewImage: '/templates/previews/saas-landing.jpg',
    version: '1.3.0',
    category: 'saas',
    tags: ['saas', 'pricing', 'features', 'conversion'],
    downloadUrl: 'https://templates.perissos.dev/saas-landing-v1.3.0.zip',
    author: 'Perissos Team',
    authorUrl: 'https://perissos.dev',
    rating: 4.8,
    downloads: 1923,
    lastUpdated: '2026-01-10',
  },
  {
    id: 'portfolio-minimal-v1',
    name: 'Minimal Portfolio',
    description: 'Clean, minimalist portfolio template for designers, photographers, and creatives. Focus on your work with beautiful gallery layouts.',
    previewImage: '/templates/previews/minimal-portfolio.jpg',
    version: '1.0.0',
    category: 'portfolio',
    tags: ['minimal', 'gallery', 'creative', 'photography'],
    downloadUrl: 'https://templates.perissos.dev/minimal-portfolio-v1.0.0.zip',
    author: 'Sarah Chen',
    authorUrl: 'https://sarahchen.design',
    rating: 4.7,
    downloads: 1456,
    lastUpdated: '2025-12-20',
  },
  {
    id: 'business-consulting-v1',
    name: 'Business Consulting',
    description: 'Professional business consulting template with services, case studies, team, and contact sections. Ideal for consulting firms.',
    previewImage: '/templates/previews/business-consulting.jpg',
    version: '1.2.0',
    category: 'business',
    tags: ['corporate', 'services', 'case-studies', 'team'],
    downloadUrl: 'https://templates.perissos.dev/business-consulting-v1.2.0.zip',
    author: 'Perissos Team',
    authorUrl: 'https://perissos.dev',
    rating: 4.6,
    downloads: 987,
    lastUpdated: '2025-12-15',
  },
  {
    id: 'ecommerce-fashion-v1',
    name: 'Fashion E-commerce',
    description: 'Elegant fashion store template with product grid, categories, featured products, and checkout-ready layout.',
    previewImage: '/templates/previews/ecommerce-fashion.jpg',
    version: '1.0.0',
    category: 'ecommerce',
    tags: ['fashion', 'shop', 'products', 'categories'],
    downloadUrl: 'https://templates.perissos.dev/ecommerce-fashion-v1.0.0.zip',
    author: 'Marco Rossi',
    authorUrl: 'https://marcorossi.dev',
    rating: 4.5,
    downloads: 734,
    lastUpdated: '2025-11-30',
  },
  {
    id: 'blog-magazine-v1',
    name: 'Magazine Blog',
    description: 'Content-rich magazine-style blog template with featured posts, categories, newsletter signup, and author profiles.',
    previewImage: '/templates/previews/magazine-blog.jpg',
    version: '1.1.0',
    category: 'blog',
    tags: ['magazine', 'news', 'newsletter', 'categories'],
    downloadUrl: 'https://templates.perissos.dev/magazine-blog-v1.1.0.zip',
    author: 'Perissos Team',
    authorUrl: 'https://perissos.dev',
    rating: 4.7,
    downloads: 1102,
    lastUpdated: '2025-12-05',
  },
  {
    id: 'startup-landing-v1',
    name: 'Startup Launch',
    description: 'Pre-launch startup landing page with countdown timer, email capture, features, and social proof sections.',
    previewImage: '/templates/previews/startup-landing.jpg',
    version: '1.0.0',
    category: 'landing',
    tags: ['startup', 'launch', 'countdown', 'email-capture'],
    downloadUrl: 'https://templates.perissos.dev/startup-landing-v1.0.0.zip',
    author: 'Alex Kim',
    authorUrl: 'https://alexkim.design',
    rating: 4.4,
    downloads: 567,
    lastUpdated: '2025-11-20',
  },
]

export async function GET() {
  try {
    return NextResponse.json({
      templates: marketplaceTemplates,
      total: marketplaceTemplates.length,
      categories: [
        'all',
        'agency',
        'business',
        'portfolio',
        'blog',
        'ecommerce',
        'landing',
        'saas',
      ],
    })
  } catch (error: any) {
    console.error('Marketplace fetch error:', error)
    return NextResponse.json(
      { error: 'Failed to fetch marketplace templates' },
      { status: 500 }
    )
  }
}
